### ISSUE TITLE
Improve layout interface for programmatic construction of charts 

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#274]
see https://github.com/ScottLogic/d3-financial-components/pull/265#issuecomment-72372148

**Comment by chrisprice** [comment]
Other issues I've faced with layout -
* Some elements (e.g. ```rect``` and ```svg```) have more appropriate attributes for the x/y/width/height values (rather than ```layout-width/height``` and ```transform=translate...```.
* I'd like to be able to call layout on a subset of previously laid-out elements (e.g. to reflow a small part of the layout). This requires a way to pass the previously calculated width and height into the layout somehow.
* The layout is trashing other transform values (e.g. rotating text labels).

Not sure if they all need to be solved by layout but thought I'd mention them here.

**Comment by chrisprice** [comment]
Another one -

* Currently accessing a resulting width/height returns a string value (it's been round-tripped via an attribute), it would be better if it was forced to a number (otherwise feeding it into a scale range gives string results...)

**Comment by ColinEberhardt** [comment]
I've come to the uncomfortable realisation that this probably needs unit tests  :-/

**Comment by ColinEberhardt** [comment]
> The layout is trashing other transform values (e.g. rotating text labels).

This is a tricky one to fix. The layout could just add its transforms to any that are already present, however - we want our components to be idempotent, so if invoked multiple times it would need to know which ones had been added via layout and which were already there.

**Comment by chrisprice** [comment]
I suppose setting x/y on text nodes would solve the particular problem I'm having?

**Comment by jleft** [comment]
More thoughts here: https://github.com/ScottLogic/d3-financial-components/pull/285#issuecomment-73720583

**Comment by chrisprice** [comment]
fb5d87ea added support for width/height/x/y on rect/svg elements.
